version: "3"

services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./data/
        target: /app/data/
      - type: bind
        source: ./conf.toml
        target: /app/conf.toml
    ports:
      - "8449:8000"
    entrypoint: ["python", "./launcher.py", "conf.toml"]
