command_prefix = "!"

desc = "hallo wie gehts schlecht :("

owner_id = 123

guild_id = 123

[api_tokens]

discord = "abc"
news_api_key = "abc"
weather_api_key = "abc"
twitter_api_key = "abc"
twitter_api_secret = "abc"
twitter_bearer_token = "abc"
alpaca_api_key_id = "abc"
alpaca_api_key_secret = "abc"
openai_api_key = "abc"
openai_org_id = "abc"
brevo_api_key = "abc"